### ISSUE TITLE
Issue accessing HeapInc.Xamarin.iOS with .net MAUI

### ISSUE THREAD

**Issue by brendan-holly-modea** [heap/heap-xamarin-bridge-sdk#2]
# Error accessing the iOS implementation of Heap at `Heapinc.Xamarin.iOS` to initialize the tracker

## The problem

When I attempt to add tracker initialization to the iOS app delegate as part of a .net MAUI build, I am getting a consistent build issue.

Code
```csharp
public override bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
{
     HeapInc.Xamarin.iOS.Implementation.StartRecording("YOUR_ENVIRONMENT_ID");
     return base.FinishedLaunching(application, launchOptions);
}
```

Error
```xaml
AppDelegate.cs(14,9): Error CS0234 :
The type or namespace name 'iOS' does not exist in the namespace 'HeapInc.Xamarin' (are you missing an assembly reference?)
```

## My system

I have created a [reproduction repo](https://github.com/brendan-holly-modea/heap-implementation-test) from the initial .net MAUI app pointing to .net 8. I am working on an arm64 mac.

## Attempted solutions

I have tried cleaning, rebuilding, reinstalling the nuget packages, and restarting my mac.

These [lines from the documentation](https://developers.heap.io/docs/xamarin-quick-start) are confusing:

> If your application uses .NET MAUI, the Heap Xamarin Bridge will work for your app as well. 
> To enable building with .NET MAUI, raise your project's target framework to .NET Standard 2.1, clean, and rebuild.

MAUI apps target .net core not .net standard. We cannot change the project's target framework from .net 8 to .net standard 2.1.

Thank you for your time!

**Comment by MCeley** [comment]
Can you try using [this](https://www.nuget.org/packages/HeapInc.Maui) instead?

**Comment by brendan-holly-modea** [comment]
@MCeley this combined with the [updated documentation](https://developers.heap.io/docs/xamarin-quick-start) is working well on the sample app. Thank you very much for the help!
